### ISSUE TITLE
Add firebase Crashlytics for crash reporting

### ISSUE THREAD

**Issue by eiarhabi** [PassionPenguin/Ditiezu#5]
As described in title. Firebase is available in China and it would help keeping track of all the crashes.

**Comment by PassionPenguin** [comment]
Thanks!
But.. How to use the Crashlytics?
I've finished pasting scripts -> APP, but the interface on the site(https://console.firebase.google.com/u/0/project/ditiezu-android/crashlytics/app/android:com.passionpenguin.ditiezu/issues) kept loading

**Comment by PassionPenguin** [comment]
Initialized

**Comment by PassionPenguin** [comment]
Thanks for your advice~
