### ISSUE TITLE
Overlapping items in item_reply_item.xml

### ISSUE THREAD

**Issue by eiarhabi** [PassionPenguin/Ditiezu#6]
reference:
http://www.ditiezu.com/forum.php?mod=redirect&goto=findpost&ptid=679983&pid=11789367&fromuid=750092

Probably the issue is here:
https://github.com/Ditiezu/Android/blob/cb243780d4316a5e0400a9f4d0bf0189d74e73ee/app/src/main/res/layout/item_reply_item.xml#L58

Maybe it would be better if the three checkboxes can be placed under `threadMetaInfo` item

**Comment by PassionPenguin** [comment]
Thanks for your issue.
I've known that problem since I've met it with a pretty small phone...
I will then look at other apps and try to rearrange these buttons~

**Comment by PassionPenguin** [comment]
Fixed by reducing size.
Will be fixed in next-gen design.
