### ISSUE TITLE
English translation issue for the interface

### ISSUE THREAD

**Issue by Fourthbus** [PassionPenguin/Ditiezu#8]
Hi, I just noticed there are several translation issues in slightly confusing translations in the interface in English. Here are a few I noticed and some suggestions for improvements:

「綜合區」 might be translated as ‘General’
「海外區」 may be ‘Overseas’ or ‘International' instead of 'Oversea'
The meaning of「意見建議」 means more closely to ‘Feedback’, although I suppose the developer just made it by mistakenly copy and paste the previous section without amending.

These are just some final vanishings with low priority so don't worry too much about them.

Thanks!

**Comment by PassionPenguin** [comment]
sorry for that problem, but now it's been totally Simplified Chinese Values, maybe this problem may be fixed later.
